### ISSUE TITLE
Samples don't import cleanly

### ISSUE THREAD

**Issue by codek** [PacktPublishing/Learning-Pentaho-CTools#1]
Hi, these samples dont import cleanly. The directory structure in Git doesnt match what is expected by the files in the Pentaho repository - partly because the Pentaho solution files have spaces in them etc.

It would be ideal if it was all rationalised so that you could just import the files as they are without renaming etc.

**Comment by codek** [comment]
This bug is the cause of the problems: https://jira.pentaho.com/browse/CDA-126

So; when you import, just rename all the + to spaces and it then works.

Oh, and the folders have spaces, i.e. Chapter 6 not Chapter6

**Comment by packt-pradeeps** [comment]
Thank you for informing.
